name: Run Python Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check Chrome version
      run: |
        google-chrome --version

    - name: Test with pytest and generate junit xml report
      run: |
        pytest tests --junitxml report.xml
      env:
        CICD_RUN: "yes"
      
    - name: Create test summary
      uses: test-summary/action@v1.0
      with:
        paths: report.xml
      if: always()
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "report.xml"
